"""update models

Revision ID: 52c37f6f58d9
Revises: edbd0000f306
Create Date: 2024-04-19 21:33:45.799485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c37f6f58d9'
down_revision: Union[str, None] = 'edbd0000f306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'bio',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('books', sa.Column('title', sa.String(length=63), nullable=False))
    op.alter_column('books', 'summary',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('books', 'tittle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('tittle', sa.VARCHAR(length=63), nullable=False))
    op.alter_column('books', 'summary',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('books', 'title')
    op.alter_column('authors', 'bio',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
